# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

## Project team
<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?

Describe each member of the team (including advisors) and the skills they bring to the project.
-->

**Jason Cory Brunson, PhD**
(Project Co-lead):
Dr. Brunson (Assistant Professor, University of Florida) is a mathematician by training with a long-running interest in topological data analysis. He has authored or contributed to several TDA packages on CRAN, including {TDAstats}, {ripserr}, {simplextree}, {tdaunif}, the last of which he maintains.
He also has two feature-complete packages in preparation, a {ggplot2} extension for topological data[^ggtda] and an R interface to the Persistence Landscapes Toolbox[^plt].

**Aymeric Stamm, PhD**
(Project Co-lead):
Dr. Stamm (Research Engineer, CNRS, France) is a mathematical engineer by training with specialisation in statistics.
<!--
including statistical information. As a mathematician, he has been working on geometry-informed statistical inference for complex objects (functional data, network-valued data, manifold-valued data) from a theoretical point of view and contributed several real-life applications as well. As an engineer, he has authored or contributed to many packages not all related to TDA.
-->
He is in particular the author and maintainer of the {rgudhi} package which ports the GUDHI library into R and of the {flipr} package for permutation-based inference. He has extensive expertise on efficient programming in R including optimisation of R code, use of C/C++ code through {Rcpp} and parallelisation of either R or C++ code.

**Paul Rosen, PhD**
(Advisory Board Member):
Dr. Rosen (Associate Professor, University of Utah) is a computer scientist who focuses on geometric and topological approaches in scientific and information visualization and has authored several computational tools for TDA.

**Bertrand Michel, PhD**
(Advisory Board Member):
Dr. Michel (Professeur, l'Ecole Centrale Nantes) researches statistical learning and is interested in statistical methods for geometric and topological inference. He coauthored {flipr} with Dr. Stamm and others.

## Contributors
<!-- 
Who are the people who have actively helped with this proposal but won't necessarily be on the core project team later?
-->

Several related packages are published on CRAN, installable from GitHub, or in development.
Major contributors include Raoul Wadhwa (Cleveland Clinic Lerner College of Medicine, Case Western Reserve University), Matt Piekenbrock (Khoury College of Computer Sciences, Northeastern University), Yara Skaf (College of Medicine, University of Florida), and James Otto (Department of Statistical Science, Baylor University).

## Consulted
<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->

We have solicited feedback on drafts of this proposal from members of (1) the Topological Data Analysis Discussion Group at the University of Florida[^tda-discussion], (2) the Laboratory for Systems Medicine at the University of Florida[^lsm], and (3) presenters at UFTDA2024[^uftda2024], a conference organized by the Bubenik lab and hosted at the University of Florida.

[^tda-discussion]: <https://people.clas.ufl.edu/nikola/topological-data-analysis-discussion-group/>
[^lsm]: <https://systemsmedicine.pulmonary.medicine.ufl.edu/>
[^uftda2024]: <https://people.clas.ufl.edu/peterbubenik/uftda2024/>
