# The Problem
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Whom it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->

R is one of the most widely used programming languages in statistics. It is used by professionals ranging from data analysts to educators to research statisticians, to implement newly developed methods and facilitate hands-on learning as well as to conduct routine analyses.
Topological data analysis is an emerging and heterogeneous area of statistical research that is grounded in the mathematical discipline of topology. It intersects heavily with exploratory analysis and visualization, statistical inference, and machine learning.
It is therefore important to the currency of mainstream statistical work and to ongoing methods development for R users to have access to comprehensive and reliable TDA tools.

At present, this is not the case.
Feedback from colleagues has been consistent on the following points.
Regarding TDA software in general:

1. Most techniques used in TDA are not easily accessible or well documented and require significant training or experimentation to use.
2. Most practitioners implement at least some tools described in published studies from scratch.

Regarding solutions to the problems motivating this proposal:

3. No software resource provides a comprehensive set of vectorization methods for persistence data.
4. Most hypothesis-testing work is conducted using original _ad hoc_ code.
5. Practitioners frequently use (various implementations or ports of) Ripser in longer computational pipelines that would otherwise be impractical.

This feedback suggests that practitioners face challenges when using TDA software that, though they are overcome by specialists, are likely to be daunting to non-specialist researchers and analysts.

Published R packages for TDA fall into three categories:
First, {TDA} and {rgudhi} provide interfaces to comprehensive libraries in lower-level languages, including GUDHI, Dionysus, and PHAT.
While they provide essential tools to users---{TDA} is the most frequently downloaded of the packages surveyed here---they are not designed to integrate with common tools and workflows outside TDA.
<!--For example, they return output as lists rather than as classes with `print()` and `summary()` methods.-->
They are also made fragile by the need to adapt to upgrades both in the source code language and in R.
<!--Both packages have been removed from CRAN in the past year due to emergent issues not being corrected in time.-->
Second, {TDAstats}, {TDAkit}, {TDApplied}, and {GSSTDA} provide bespoke toolkits for statistical inference, machine learning, and survival analysis.
These packages tend to be designed for specialists rather than general users, self-contained rather than modular, syntactically inharmonious with common workflows, and reliant on libraries written in other languages.
These limitations have likely hindered the adoption of TDA approaches by non-specialists; for example, an Rseek search for "topological data analysis" returns a handful of commentaries, tutorials, and workshop notes, most of which use only one package and all of which are several years old.[^search]
<!--There is limited funding for maintaining TDA software, which certainly contributes to the small number and idiosyncrasy of available packages, and this may in part be because a critical mass of users has not emerged.-->

[^search]: <https://blog.revolutionanalytics.com/2014/01/topological-data-analysis-with-r.html>, <https://rviews.rstudio.com/2018/11/14/a-mathematician-s-perspective-on-topological-data-analysis-and-r/>, <https://calebntorres.github.io/pdf/TDA.pdf>, <https://people.clas.ufl.edu/peterbubenik/files/tda_r_workshop.pdf>, <https://gist.github.com/rrrlw/2fd22a834a883cb66454b1dabab9fdcb>

A third category of TDA packages fit a different profile, in that each package performs a narrow task: {simplextree} provides the simplex tree data structure, {interplex} converts between this and other data structures for simplicial complexes, {ripserr} interfaces to the Ripser algorithm to compute persistent homology, and {tdaunif} provides uniform samplers for topologically interesting spaces.
These packages have been developed by Dr. Brunson and colleagues with the goal of building a general-purpose, native, modular, interoperable, and extensible R package collection for TDA.
They are not as comprehensive as the first category, and they are not yet as interoperable and extensible as envisioned.
In order to meet the needs of non-specialists, the collection will need to resolve its own incompatibilities and be integrated into more widely used data analysis tools.

[^TDA]: <https://cran.r-project.org/package=TDA>
[^rgudhi]: <https://cran.r-project.org/package=rgudhi>
[^TDAstats]: <https://cran.r-project.org/package=TDAstats>
[^TDAkit]: <https://cran.r-project.org/package=TDAkit>
[^TDApplied]: <https://cran.r-project.org/package=TDApplied>
[^GSSTDA]: <https://cran.r-project.org/package=GSSTDA>
[^cranlogs]: 718/month as of 2024 Jan 26
[^simplextree]: <https://cran.r-project.org/package=simplextree>
[^interplex]: <https://cran.r-project.org/package=interplex>
[^ripserr]: <https://cran.r-project.org/package=ripserr>
[^tdaunif]: <https://cran.r-project.org/package=tdaunif>
[^plt]: <https://github.com/corybrunson/plt>
[^ggtda]: <https://github.com/tdaverse/ggtda>
[^tdaverse-list]: <https://github.com/tdaverse/tdaverse>
