# The proposal
<!--
This is where the proposal should be outlined. 
-->

The **goal** of this pilot is to publish or republish 1--3 packages that seamlessly integrate popular techniques from topological data analysis (TDA) into common statistical workflows in R.
The **expected benefit** is that these extensions will be downloaded and used by researchers and analysts with no specialized background in TDA, which will expose them and their communities to the broader package collection and create sufficient awareness, interest, and demand for users to request features and contribute to the packages.

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

Tidymodels[^tidymodels] provides a complete machine learning toolkit for the most common prediction tasks.
Analyses can be extended to handle less common needs, such as by using time-to-event models and customizing performance metrics.
Machine learning relies heavily on the use of pre-processing steps, especially vectorization, and the last decade of work in TDA has produced several such methods based on persistent homology.
None of these are currently available to Tidymodels users, and our **first aim** is to close that gap.

[^tidymodels]: <https://www.tidymodels.org/>

Outside machine learning, TDA relies heavily on permutation-based statistical inference.
A variety of hypothesis tests have been proposed in the research literature, but they are implemented in several languages, and those in R rarely take advantage of standard conventions.
Our **second aim** is to provide an extensible package for permutation-based hypothesis testing with topological data and integrate it into Tidymodels workflows.

The primary workhorse for TDA (underpinning both above topics) is persistent homology, and the primary algorithm for persistent homology is Ripser, which efficiently computes Vietoris--Rips filtrations.[^ripser]
The standalone wrapper {ripserr} is method- and dependency-light and additionally interfacing to the cubical Ripser of @Kaji2020, making it a preferable option for many analysis scripts and higher-level packages that don't rely on the wealth of other tools provided by {TDA} and {rgudhi}.
However, the Ripser engine used in {ripserr} is out of date and missing key features, so our **third aim** is to upgrade it.

## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

**Aim 1:**
Publish a {recipes} extension for vectorizations and other transformations based on persistent homology that have been used to pre-process data for machine learning.

Several pre-processing extensions have been published for Tidymodels, including {embed}, {themis}, and {textrecipes}.[^recipes-extensions]
The new package would provide `step_*()` functions for several existing topological transformations and invite users to contribute additional steps.
Dr. Brunson has experience writing such an extension, for association rules, which satisfies checks but is not published.[^arulesteps]

[^arulesteps]: <https://github.com/corybrunson/arulesteps>
[^recipes-extensions]: <https://www.tidyverse.org/blog/2022/05/recipes-update-05-20222/>

Many transformations may eventually be implemented or imported [@Fasy2020; @Pun2022; @Ali2022].
In the list below, following the organizational scheme of @Ali2022, we have boldfaced the transformations we intend to include in a first release. These are selected based on their relative simplicity, the time since they were first introduced, the frequency with which they are used, and the expected time cost of implementing them or porting an existing implementation.

* Statistical vectorizations
  * **Persistence statistics** [@Ali2022]
  * Entropy summary [@Ali2022]
  * 2D histogram [@Fasy2020]
* Algebraic vectorizations
  * Algebraic functions [@Ali2022]
  * Tropical coordinate functions [@Ali2022]
  * Complex polynomial [@Ali2022]
* Curve vectorizations
  * **Betti curve** [@Fasy2020; @Ali2022]
  * **Lifespan curve** [@Ali2022]
  * **Persistence landscape** [@Fasy2020; @Ali2022]
  * Persistence silhouette [@Ali2022]
* Functional vectorizations
  * Persistence surface [@Pun2022]
  * **Persistence image** [@Fasy2020]
  * Template functions [@Ali2022]

Most selected methods would be implemented anew; the exceptons are persistence landscapes (implemented in {TDA} and in the forthcoming {plt}) and persistence images (which would be implemented in a standalone helper package adapted from the original Matlab implementation [^persistence-images]).

[^persistence-images]: <https://github.com/CSU-TDA/PersistenceImages>

**Aim 2:**
Publish a {flipr} extension for permutation-based statistical inference on topological data.

Dr. Stamm leads a coordinated package collection for permutation-based inference, with the published {flipr} package at its center. This package features

  (i) implementations of classic permutation schemes that are agnostic to the type of input through the use of lists for defining samples and
  (ii) the central `PlausibilityFunction` R6 class, which can be used seamlessly for performing an hypothesis test or a confidence region.

Extensions can then be contributed to enablepermutation-based hypothesis testing and confidence regions for specific data types. An extension for network-valued data, {nevada},[^nevada] is also published. Two other extensions, not yet published, provide support for scalar- and vector-valued data. The {fdatest} package dedicated to inference for functional data is also undergoing a complete redesign to work with {flipr}.

The new package would extend {flipr} to data types arising from TDA. Leveraging the {flipr} package, it will provide methods to perform two-sample testing, ANOVA and hypothesis tests in the context of regression (on the coefficients, or on the model itself, or for model comparison and selection). For vectorized representations of persistence homology, it will also provide confidence regions. Permutation-based hypothesis testing also features non-parametric combination (NPC) [@Pesarin2010], which enables the use of several test statistics in a single hypothesis test, making the combination sensitive to different aspects of the compared underlying distributions. The new package will inherit this capability, giving the possibility to use several representations of persistence data and several associated metrics for performing a single more powerful test.

Base R provides the standard ‘htest’ output class for hypothesis tests, for which the Tidymodels {broom} package provides a suite of tidiers. These tools make programmatic statistical inference straightforward. A key advantage of the new package will be to extend this facility to statistical inference in TDA.

<!--
Several published packages provide statistical inference for persistence diagrams, but these are _ad hoc_ solutions for specific problems and do not provide a unified, easily extensible framework.
Dr. Stamm is co-lead on a coordinated package collection for permutation-based inference, with the published {flipr} package at its center.
An extension for network-valued data, {nevada}[^nevada], is also published.
The new package would extend {flipr} to data types arising from TDA.
-->

[^nevada]: <https://cran.r-project.org/package=nevada>

Base R provides the standard 'htest' output class for hypothesis tests, for which the Tidymodels {broom} package provides a suite of tidiers.
These tools make programmatic statistical inference straightforward.
A key advantage of the new package will be to extend this facility to statistical inference in TDA.

**Aymeric, could you expand on the specific tools this package would provide?**

<!--
Redesign {TDAstats} to specialize in hypothesis tests and better integrate into tidy workflows.

1. Remove Ripser source code and {ggplot2} plotting routines in favor of dependency on {ripserr} and {ggtda}.
2. Identify additional hypothesis tests and null models that should be included [@Robinson2017; @VejdemoJohansson2022].
3. Use standard classes and methods (e.g. class 'htest', method `print()`) to make output follow common R conventions; include {generics} methods like `tidy()`.

The following hypothesis tests are already implemented:

* permutation test for difference in means [@Robinson2017]

The following hypothesis tests may be implemented (listed in order of likely inclusion and feasibility):

* bootstrap sample hypothesis tests [@Blumberg2014]
* Z-test and permutation test for persistence landscapes [@Bubenik2015], currently implemented in {plt}
* exact topological inference [@Chung2017]
* tests for grouped point clouds [@Abdallah2023]
-->

**Aim 3:**
Refactor {ripserr} with a current implementation of Ripser and connect additional options to R.

The base implementation of Ripser is written in C++, and {ripserr} provides C++/R integration via {Rcpp}.
We therefore anticipate that this update will be a straightforward, though not trivial, exercise in C++/R integration via {Rcpp}.

A novel feature that may pose an additional challenge is the recovery of representative cocycles and/or cycles. These features did not exist when {ripserr} was first developed but are essential for many practical applications.
While an ideal interface would pass options to a single C++ function, a simpler approach is available in case this proves impractical, namely to interface to one of multiple C++ functions depending on user specifications.

[^ripser]: <https://github.com/Ripser/ripser>
