# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.

 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

<!--Platform: GitHub TDAverse account & existing package repos-->
Development will take place publicly on two GitHub accounts: TDAverse, co-owned by Dr. Brunson (Aims 1 and 3), and LMJL-Alea, co-owned by Dr. Stamm (Aim 2).
Both co-leads will have write access to the repositories for all project packages.
<!--Licenses: consistent with existing packages and Tidyverse (GPL >= 2)-->
All project packages will be licensed compatibly with R and Tidyverse/Tidymodels (MIT or GPL >= 2).
The co-leads will provide the R Consortium with monthly updates based on progress toward the deliverables below.

[^r-licenses]: <https://www.r-project.org/Licenses/>

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

Aim 1: {recipes} extension for topological data transformations (<= 16wk)

1. Assembly of external engines or original implementations of selected transformations. (<= 6wk)
2. Template {recipes} extension, to ensure that infrastructural checks are satisfied. (<= 2wk)
3. Complete implementation of a single transformation, with documentation of all necessary steps (including unit tests, documentation, and examples). (<= 2wk)
4. Implementations of remaining selected transformations. (<= 4wk)
5. Vignette illustrating complete modeling workflow using at least two transformations. (<= 2wk)

Aim 2: {flipr} extension for topological data types (<= 10wk)

1. Review and selection of a first set of metric spaces (representation + metric) into which the persistence data is to be analysed and implementation of such spaces. This will probably focus on vectorized representations, which would be assembled jointly with the {recipes} extension from Aim 1. (<= 2wk)
2. Implementations of a variety of test statistics that focus on comparing different features between distributions, either exploiting accessibility to Frechet means and variances when the metric space allows for it or resorting to statistics based on inter-point distances. (<= 2wk)
3. Implementations of confidence bands for functional representations of persistance data based on above implemented test. (<= 4wk)
4. Writing up a vignette illustrating new functionalities. (<= 2 wk)

Aim 3: {ripserr} upgrade (<= 8wk)

1. Selection and reconciliation of current Ripser implementations in C++. (<= 4wk)
2. Integration into package using {Rcpp}. (<= 2wk)
3. Updated vignette illustrating new functionality. (<= 2wk)

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

Each package release will be announced on social media platforms using the `#rstats` tag and on blogs cross-posted to R-bloggers.
We will submit abstracts for each aim to relevant conferences (e.g., useR!, `posit::conf()`, the Joint Statistical Meetings).
We will also propose in-person workshops co-located with local or regional conferences, including UFTDA.
Finally, we plan to submit at least two journal articles: one on a handful of packages that integrate with the Tidyverse (including the {recipes} extension and the nearly complete {ggplot2} extension {ggtda}), another on the {flipr} collection including its TDA extension.
